version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: peeple-api:latest
    container_name: peeple-api-container
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    environment:
      YOUR_APP_DB_HOST_ENV_VAR: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net
    restart: unless-stopped

  db:
    image: postgres:17.4-alpine3.21
    container_name: postgres_local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data: {}

networks:
  app-net:
    driver: bridge
