// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PeepleApiLike struct {
	ID         int32  `json:"id"`
	Likeremail string `json:"likeremail"`
	Likedemail string `json:"likedemail"`
}

type PeepleApiMatch struct {
	ID         int32            `json:"id"`
	User1email string           `json:"user1email"`
	User2email string           `json:"user2email"`
	Matchedat  pgtype.Timestamp `json:"matchedat"`
}

type PeepleApiMessage struct {
	ID            int32            `json:"id"`
	Senderemail   string           `json:"senderemail"`
	Receiveremail string           `json:"receiveremail"`
	Content       string           `json:"content"`
	Sentat        pgtype.Timestamp `json:"sentat"`
	Isread        pgtype.Bool      `json:"isread"`
}

type PeepleApiPicture struct {
	ID        int32  `json:"id"`
	Useremail string `json:"useremail"`
	Url       string `json:"url"`
}

type PeepleApiProfileimage struct {
	ID        int32  `json:"id"`
	Useremail string `json:"useremail"`
	Url       string `json:"url"`
	Name      string `json:"name"`
	Imageno   int32  `json:"imageno"`
}

type PeepleApiUser struct {
	ID               int32       `json:"id"`
	Name             pgtype.Text `json:"name"`
	Email            string      `json:"email"`
	Location         pgtype.Text `json:"location"`
	Gender           pgtype.Text `json:"gender"`
	Relationshiptype pgtype.Text `json:"relationshiptype"`
	Height           pgtype.Int4 `json:"height"`
	Religion         pgtype.Text `json:"religion"`
	OccupationField  pgtype.Text `json:"occupation_field"`
	OccupationArea   pgtype.Text `json:"occupation_area"`
	Drink            pgtype.Text `json:"drink"`
	Smoke            pgtype.Text `json:"smoke"`
	Bio              pgtype.Text `json:"bio"`
	Date             pgtype.Int4 `json:"date"`
	Month            pgtype.Int4 `json:"month"`
	Year             pgtype.Int4 `json:"year"`
	Subscription     pgtype.Text `json:"subscription"`
	Instaid          pgtype.Text `json:"instaid"`
	Phone            pgtype.Text `json:"phone"`
}

type PeepleApiUserpreference struct {
	ID                         int32       `json:"id"`
	Useremail                  string      `json:"useremail"`
	Agerange                   []byte      `json:"agerange"`
	Genderpreference           []byte      `json:"genderpreference"`
	Relationshiptypepreference []byte      `json:"relationshiptypepreference"`
	Maxdistance                pgtype.Int4 `json:"maxdistance"`
}
