// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddLike(ctx context.Context, arg AddLikeParams) (PeepleApiLike, error)
	AddUserPicture(ctx context.Context, arg AddUserPictureParams) (PeepleApiPicture, error)
	CreateUser(ctx context.Context, email string) (PeepleApiUser, error)
	GetMutualLikes(ctx context.Context, likeremail string) ([]GetMutualLikesRow, error)
	GetSubscription(ctx context.Context, email string) (pgtype.Text, error)
	GetUserByEmail(ctx context.Context, email string) (PeepleApiUser, error)
	GetUserLikers(ctx context.Context, likedemail string) ([]GetUserLikersRow, error)
	GetUserPictures(ctx context.Context, useremail string) ([]string, error)
	ListAllUsers(ctx context.Context) ([]PeepleApiUser, error)
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (PeepleApiUser, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (PeepleApiUser, error)
}

var _ Querier = (*Queries)(nil)
