// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addLike = `-- name: AddLike :one
INSERT INTO peeple_api_likes (likerEmail, likedEmail)
VALUES ($1, $2)
RETURNING id, likeremail, likedemail
`

type AddLikeParams struct {
	Likeremail string `json:"likeremail"`
	Likedemail string `json:"likedemail"`
}

func (q *Queries) AddLike(ctx context.Context, arg AddLikeParams) (PeepleApiLike, error) {
	row := q.db.QueryRow(ctx, addLike, arg.Likeremail, arg.Likedemail)
	var i PeepleApiLike
	err := row.Scan(&i.ID, &i.Likeremail, &i.Likedemail)
	return i, err
}

const addUserPicture = `-- name: AddUserPicture :one
INSERT INTO peeple_api_pictures (userEmail, url)
VALUES ($1, $2)
RETURNING id, useremail, url
`

type AddUserPictureParams struct {
	Useremail string `json:"useremail"`
	Url       string `json:"url"`
}

func (q *Queries) AddUserPicture(ctx context.Context, arg AddUserPictureParams) (PeepleApiPicture, error) {
	row := q.db.QueryRow(ctx, addUserPicture, arg.Useremail, arg.Url)
	var i PeepleApiPicture
	err := row.Scan(&i.ID, &i.Useremail, &i.Url)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO peeple_api_users (email)
VALUES ($1)
RETURNING id, name, email, location, gender, relationshiptype, height, religion, occupation_field, occupation_area, drink, smoke, bio, date, month, year, subscription, instaid, phone
`

func (q *Queries) CreateUser(ctx context.Context, email string) (PeepleApiUser, error) {
	row := q.db.QueryRow(ctx, createUser, email)
	var i PeepleApiUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Location,
		&i.Gender,
		&i.Relationshiptype,
		&i.Height,
		&i.Religion,
		&i.OccupationField,
		&i.OccupationArea,
		&i.Drink,
		&i.Smoke,
		&i.Bio,
		&i.Date,
		&i.Month,
		&i.Year,
		&i.Subscription,
		&i.Instaid,
		&i.Phone,
	)
	return i, err
}

const getMutualLikes = `-- name: GetMutualLikes :many
SELECT DISTINCT u.name, u.instaid, u.phone, p.url as photo_url
FROM peeple_api_likes l1
JOIN peeple_api_likes l2 ON l1.likerEmail = l2.likedEmail AND l1.likedEmail = l2.likerEmail
JOIN peeple_api_users u ON l2.likerEmail = u.email
LEFT JOIN peeple_api_pictures p ON u.email = p.email
WHERE l1.likerEmail = $1
`

type GetMutualLikesRow struct {
	Name     pgtype.Text `json:"name"`
	Instaid  pgtype.Text `json:"instaid"`
	Phone    pgtype.Text `json:"phone"`
	PhotoUrl pgtype.Text `json:"photo_url"`
}

func (q *Queries) GetMutualLikes(ctx context.Context, likeremail string) ([]GetMutualLikesRow, error) {
	rows, err := q.db.Query(ctx, getMutualLikes, likeremail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMutualLikesRow{}
	for rows.Next() {
		var i GetMutualLikesRow
		if err := rows.Scan(
			&i.Name,
			&i.Instaid,
			&i.Phone,
			&i.PhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscription = `-- name: GetSubscription :one
SELECT subscription FROM peeple_api_users
WHERE email = $1
`

func (q *Queries) GetSubscription(ctx context.Context, email string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getSubscription, email)
	var subscription pgtype.Text
	err := row.Scan(&subscription)
	return subscription, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, location, gender, relationshiptype, height, religion, occupation_field, occupation_area, drink, smoke, bio, date, month, year, subscription, instaid, phone FROM peeple_api_users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (PeepleApiUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i PeepleApiUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Location,
		&i.Gender,
		&i.Relationshiptype,
		&i.Height,
		&i.Religion,
		&i.OccupationField,
		&i.OccupationArea,
		&i.Drink,
		&i.Smoke,
		&i.Bio,
		&i.Date,
		&i.Month,
		&i.Year,
		&i.Subscription,
		&i.Instaid,
		&i.Phone,
	)
	return i, err
}

const getUserLikers = `-- name: GetUserLikers :many
SELECT u.email, u.name
FROM peeple_api_likes l
JOIN peeple_api_users u ON l.likerEmail = u.email
WHERE l.likedEmail = $1
`

type GetUserLikersRow struct {
	Email string      `json:"email"`
	Name  pgtype.Text `json:"name"`
}

func (q *Queries) GetUserLikers(ctx context.Context, likedemail string) ([]GetUserLikersRow, error) {
	rows, err := q.db.Query(ctx, getUserLikers, likedemail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserLikersRow{}
	for rows.Next() {
		var i GetUserLikersRow
		if err := rows.Scan(&i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPictures = `-- name: GetUserPictures :many
SELECT url FROM peeple_api_pictures
WHERE userEmail = $1
`

func (q *Queries) GetUserPictures(ctx context.Context, useremail string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPictures, useremail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, name, email, location, gender, relationshiptype, height, religion, occupation_field, occupation_area, drink, smoke, bio, date, month, year, subscription, instaid, phone FROM peeple_api_users
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]PeepleApiUser, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PeepleApiUser{}
	for rows.Next() {
		var i PeepleApiUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Location,
			&i.Gender,
			&i.Relationshiptype,
			&i.Height,
			&i.Religion,
			&i.OccupationField,
			&i.OccupationArea,
			&i.Drink,
			&i.Smoke,
			&i.Bio,
			&i.Date,
			&i.Month,
			&i.Year,
			&i.Subscription,
			&i.Instaid,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE peeple_api_users
SET subscription = $1
WHERE email = $2
RETURNING id, name, email, location, gender, relationshiptype, height, religion, occupation_field, occupation_area, drink, smoke, bio, date, month, year, subscription, instaid, phone
`

type UpdateSubscriptionParams struct {
	Subscription pgtype.Text `json:"subscription"`
	Email        string      `json:"email"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (PeepleApiUser, error) {
	row := q.db.QueryRow(ctx, updateSubscription, arg.Subscription, arg.Email)
	var i PeepleApiUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Location,
		&i.Gender,
		&i.Relationshiptype,
		&i.Height,
		&i.Religion,
		&i.OccupationField,
		&i.OccupationArea,
		&i.Drink,
		&i.Smoke,
		&i.Bio,
		&i.Date,
		&i.Month,
		&i.Year,
		&i.Subscription,
		&i.Instaid,
		&i.Phone,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE peeple_api_users
SET name = $1,
    location = $2,
    gender = $3,
    relationshiptype = $4,
    height = $5,
    religion = $6,
    occupation_field = $7,
    occupation_area = $8,
    drink = $9,
    smoke = $10,
    bio = $11,
    date = $12,
    month = $13,
    year = $14,
    instaid = $15,
    phone = $16
WHERE email = $17
RETURNING id, name, email, location, gender, relationshiptype, height, religion, occupation_field, occupation_area, drink, smoke, bio, date, month, year, subscription, instaid, phone
`

type UpdateUserParams struct {
	Name             pgtype.Text `json:"name"`
	Location         pgtype.Text `json:"location"`
	Gender           pgtype.Text `json:"gender"`
	Relationshiptype pgtype.Text `json:"relationshiptype"`
	Height           pgtype.Int4 `json:"height"`
	Religion         pgtype.Text `json:"religion"`
	OccupationField  pgtype.Text `json:"occupation_field"`
	OccupationArea   pgtype.Text `json:"occupation_area"`
	Drink            pgtype.Text `json:"drink"`
	Smoke            pgtype.Text `json:"smoke"`
	Bio              pgtype.Text `json:"bio"`
	Date             pgtype.Int4 `json:"date"`
	Month            pgtype.Int4 `json:"month"`
	Year             pgtype.Int4 `json:"year"`
	Instaid          pgtype.Text `json:"instaid"`
	Phone            pgtype.Text `json:"phone"`
	Email            string      `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (PeepleApiUser, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Location,
		arg.Gender,
		arg.Relationshiptype,
		arg.Height,
		arg.Religion,
		arg.OccupationField,
		arg.OccupationArea,
		arg.Drink,
		arg.Smoke,
		arg.Bio,
		arg.Date,
		arg.Month,
		arg.Year,
		arg.Instaid,
		arg.Phone,
		arg.Email,
	)
	var i PeepleApiUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Location,
		&i.Gender,
		&i.Relationshiptype,
		&i.Height,
		&i.Religion,
		&i.OccupationField,
		&i.OccupationArea,
		&i.Drink,
		&i.Smoke,
		&i.Bio,
		&i.Date,
		&i.Month,
		&i.Year,
		&i.Subscription,
		&i.Instaid,
		&i.Phone,
	)
	return i, err
}
