name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image with Podman
        run: |
          podman build -t ghcr.io/${{ github.repository }}:latest .
          podman push ghcr.io/${{ github.repository }}:latest

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          ENV_FILE: ${{ secrets.ENV_FILE_CONTENTS }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          echo "$EC2_SSH_KEY" > ec2_key
          chmod 700 ec2_key

          ssh -i ec2_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $EC2_USER@$EC2_HOST << 'EOF'
            echo "$ENV_FILE" > .env
            
            echo "$GHCR_TOKEN" | podman login ghcr.io -u ${{ github.actor }} --password-stdin
            
            podman pull ghcr.io/${{ github.repository }}:latest
            
            podman stop peeple || true
            podman rm peeple || true
            
            podman run -d --restart=always -p 8080:8080 --env-file ./.env --name peeple ghcr.io/${{ github.repository }}:latest
          EOF
